name: CI
on: [push]
jobs:
  pyright:
    name: pyright lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jakebailey/pyright-action@v2
        with:
          project: pyproject.toml
  ruff:
    name: ruff lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: src
   
