name: push ci
on: [push]
jobs:
  pyright:
    name: pyright check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jakebailey/pyright-action@v2
        with:
          working-directory: helix-python-conf
          project: pyproject.toml
  ruff:
    name: ruff check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: helix-python-conf
          args: 'format --check'
    
